spring:
  jap:
    database: h2
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create
    proprtties:
      hibernate:
        format-sql: false
        # default_batch_fetch_size: 10
  datascource:
    url: jdbc:h2:men:portfolio
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console